export const cauroselImages=[
    {
        id: 1,
        tag: "hero-product",
        tagline: "Featherweight for comfort all-day.",
        heroImage: "../images/products/boat131-3.png",
    
        images: [
            "/images/products/boat131-1.png",
            "/images/products/boat131-2.png",
            "/images/products/boat131-3.png",
            "/images/products/boat131-4.png",
        ],
        brand: "boAt",
        title: "boAt Airdopes 131",
        info: "Wireless In-Ear Earbuds",
        category: "Earbuds",
        type: "In Ear",
        connectivity: "Wireless",
        finalPrice: 1099,
        originalPrice: 2990,
        quantity: 1,
        ratings: 1244,
        rateCount: 5,
        path: "/product-details/",
    },
    {
        id: 2,
        tag: "hero-product",
        tagline: "Featherweight for comfort all-day.",
        image: "../images/products/boat131-3.png",
        images: [
            "../images/products/boat131-1.png",
            "../images/products/boat131-2.png",
            "../images/products/boat131-3.png",
            "../images/products/boat131-4.png",
        ],
        brand: "boAt",
        title: "boAt Airdopes 131",
        info: "Wireless In-Ear Earbuds",
        category: "Earbuds",
        type: "In Ear",
        connectivity: "Wireless",
        finalPrice: 1099,
        originalPrice: 2990,
        quantity: 1,
        ratings: 1244,
        rateCount: 5,
        path: "/product-details/",
    },
    {
        id: 3,
        tag: "hero-product",
        tagline: "Give your favourite music a boost.",
        images: "../images/products/sonyxb910n-1 (1).png",
        images: [
            "../images/products/sonyxb910n-1.png",
            "../images/products/sonyxb910n-2.png",
            "../images/products/sonyxb910n-3.png",
            "../images/products/sonyxb910n-4.png",
        ],
        brand: "Sony",
        title: "Sony WH-XB910N",
        info: "Wireless Over-Ear Headphones",
        category: "Headphones",
        type: "Over Ear",
        connectivity: "Wireless",
        finalPrice: 13489,
        originalPrice: 19990,
        quantity: 1,
        ratings: 679,
        rateCount: 4,
        path: "/product-details/",
    },
    
    
        
    ]